server:
  port: 7002
eureka:
  instance:
    hostname: 7002eureka
  client:
    #注册
    register-with-eureka: false
    #表示自己就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

